name: Deploy Application

on:
  push: 
  branches:
    - main
    - staging

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps: 
      - users: actions/checkout@v2

      - name: Compile CSS and JS
        run : |
          npm install
          npm run prod
