name: 'Deploy on push'

on:
  push:
    branches:  
      - main

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          api_key: ${{ secrets.FORGE_API_TOKEN }}
          server_id: ${{ secrets.FORGE_SERVER_ID }}
          site_id: ${{ secrets.FORGE_PROD_SITE_ID }}
